version: '3.8'

services:
  hello-world-app:
    build:
      context: ../../
      dockerfile: infrastructure/docker/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/hello", "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    networks:
      - hello-world-network

  hello-world-dev:
    build:
      context: ../../
      dockerfile: infrastructure/docker/Dockerfile
      target: builder
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
    volumes:
      - ../../src/backend:/app
    command: ["npm", "run", "dev"]
    restart: unless-stopped
    networks:
      - hello-world-network

networks:
  hello-world-network:
    driver: bridge