name: Release

on:
  release:
    types: [created]

jobs:
  publish_npm:
    name: Publish to npm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org/'
          cache: 'npm'
          cache-dependency-path: 'src/backend/package-lock.json'
          
      - name: Install dependencies
        run: npm ci
        working-directory: src/backend
        
      - name: Run tests
        run: npm test
        working-directory: src/backend
        
      - name: Publish to npm
        run: npm publish
        working-directory: src/backend
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          
  publish_docker:
    name: Publish to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Extract version
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
        
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./infrastructure/docker/Dockerfile
          push: true
          tags: username/nodejs-hello-world:latest,username/nodejs-hello-world:${{ steps.get_version.outputs.VERSION }}